### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by camhart** [VirgilSecurity/encryption-demo-js#5]
npm start / node server.js produces:
```
camhart73@penguin:~/playground/demo-encryption-js$ npm start

> demo-encryption-js@1.0.0 start /home/camhart73/playground/demo-encryption-js
> node server.js

internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '../virgil_crypto_node.node'
```

I'd love it if you guys would just host this somewhere.

**Comment by xlewkanx** [comment]
Hi @camhart73!

Is `npm install` ended successfully? This error could happen because newest versions of Node.js for this repository is not supported.

Anyway, this is an old demo written with [https://github.com/virgilsecurity/virgil-sdk-javascript](https://github.com/virgilsecurity/virgil-sdk-javascript) on client side.

Now you we suggest to use `virgil-sdk` for backend and [virgil-e3kit](https://github.com/virgilsecurity/virgil-e3kit-js) for client side, which is more easier to set up and has [a lot of cool features](https://virgilsecurity.com/e3kit/).

Also you always can find actual demos and resources in [awesome-virgil repository](https://github.com/VirgilSecurity/awesome-virgil).

I propose you to start with:
https://github.com/VirgilSecurity/demo-backend-nodejs
https://github.com/VirgilSecurity/demo-e3kit-web
